export default {
	REGISTERING: 'REGISTERING',
	REGISTERED: 'REGISTERED',
	REGISTER_FAIL: 'REGISTER_FAIL',

	LOGGING: 'LOGGING',
	LOGGED: 'LOGGED',
	LOGIN_FAIL: 'LOGIN_FAIL',

	UPDATING: 'UPDATING',
	UPDATED: 'UPDATED',
	UPDATE_FAIL: 'UPDATE_FAIL',
};
